/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMeSection: typeof import('./src/components/AboutMeSection.vue')['default']
    AdmonitionBlock: typeof import('./src/components/AdmonitionBlock.vue')['default']
    ArticleFooter: typeof import('./src/components/ArticleFooter.vue')['default']
    ArticleHeader: typeof import('./src/components/ArticleHeader.vue')['default']
    ArticleLayout: typeof import('./src/components/ArticleLayout.vue')['default']
    ArticlesHub: typeof import('./src/components/ArticlesHub.vue')['default']
    BaseCard: typeof import('./src/components/BaseCard.vue')['default']
    BaseTag: typeof import('./src/components/BaseTag.vue')['default']
    BulletPoint: typeof import('./src/components/BulletPoint.vue')['default']
    CardGroup: typeof import('./src/components/CardGroup.vue')['default']
    CheckboxGroup: typeof import('./src/components/CheckboxGroup.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    CodeOutput: typeof import('./src/components/CodeOutput.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DropDownMenu: typeof import('./src/components/DropDownMenu.vue')['default']
    EditArticleOnGitHub: typeof import('./src/components/EditArticleOnGitHub.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    ImageEnlarger: typeof import('./src/components/ImageEnlarger.vue')['default']
    ImageWithCaption: typeof import('./src/components/ImageWithCaption.vue')['default']
    InlineButton: typeof import('./src/components/InlineButton.vue')['default']
    InlineCode: typeof import('./src/components/InlineCode.vue')['default']
    InlineIcon: typeof import('./src/components/InlineIcon.vue')['default']
    MeteorShowers: typeof import('./src/components/MeteorShowers.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OrderedItem: typeof import('./src/components/OrderedItem.vue')['default']
    OrderedList: typeof import('./src/components/OrderedList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollBackToTop: typeof import('./src/components/ScrollBackToTop.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SeparatorImage: typeof import('./src/components/SeparatorImage.vue')['default']
    SkipLink: typeof import('./src/components/SkipLink.vue')['default']
    StarBackground: typeof import('./src/components/StarBackground.vue')['default']
    SuperscriptText: typeof import('./src/components/SuperscriptText.vue')['default']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
    ToastMessage: typeof import('./src/components/ToastMessage.vue')['default']
    ToastNotificationManager: typeof import('./src/components/ToastNotificationManager.vue')['default']
    UnorderedItem: typeof import('./src/components/UnorderedItem.vue')['default']
    UnorderedList: typeof import('./src/components/UnorderedList.vue')['default']
    VideoWithCaption: typeof import('./src/components/VideoWithCaption.vue')['default']
    YouTubePlayer: typeof import('./src/components/YouTubePlayer.vue')['default']
  }
}
